### ISSUE TITLE
Help with group page update

### ISSUE THREAD

**Issue by Anja-Pe** [zpainter/iassist#78]
Hi everyone,

I'm working in branch "update_dei_group_page" and I created a new homepage for the group but I need some help with it:

I tried to replicate the icons that we also have on IASSIST Home and in the Finding Data Guide. I copied the markdown syntax for it and I hope someone can take a look at it, whether I did everything correctly? Unfortunately, the preview doesn't show how the icons will look like in the end.

And also, where can I look up icons and pick ones that fit the context? So far I just copied everything including the icon names.

I'm including Tuomas here, too, as he helped a lot with the Finding Data Guide where I copied the syntax from :-)

Best,
Anja

**Comment by zpainter** [comment]
I edited the page, and I changed the fa-solid wording to fas. That seemed to render the icons that had something in them, but not all showed up. Other than figuring that out, the rest of the page seems correct.

I will have to poke around for where the icon names are.

**Comment by Anja-Pe** [comment]
Thanks a lot for your help, Tuomas and Zac!

It looks great so far, except the icons of course. If there's something I can do, let me know. But I wouldn't even know where to start to investigate this.

I have three more things:

- The sidebar in "Community" needs to be updated. It still says "Anti-Racism Resources" and I don't know where to change this.
- The link itself also still has "anti-racism" in there. Where can I change that?
- And I noticed that the "Finding Data Guide" page (https://iassistdata.org/community/antiracism-resources-guide/) uses breadcrumbs at the top of the page. I haven't seen it anywhere else on the IASSIST webpage. Is this something we want to start implementing or should I delete it from that page?

Best,
Anja

**Comment by talatera** [comment]
Anja,

breadcrumbs for the Finding Data Guide were a speacial, manually implemented, feature for that special page structure. It adds a third layer of navigation as the guide is quite deep and in case someone arrives there directly, there was no other visual reference for the user on where that Guide belongs. They should not appear elsewhere in that format. If the breadcumbs are not seen necessary, they can be removed.

I can edit the link structure. I assume we need to make changes in a few different spots. We don't want to simply change the name of the link, because then any outside link wouldn't work. Better to create a new page.

**Comment by Anja-Pe** [comment]
Hi Tuomas,

That makes sense with the breadcrumbs. I only looked at it from the overall website perspective. But it's fine leaving it as it is when it helps the guide.

About the link: Creating a new page would mean that the old and the new page will exist side by side? I didn't consider this before. And it may be confusing? I'm really not sure what the best option is and whether there are many links from outside. We didn't have the page for very long, I believe.
